### ISSUE TITLE
How to calculate the exact ssim？

### ISSUE THREAD

**Issue by tellMeWhyCan** [grip-unina/SAR-CNN#2]

**Comment by davin11** [comment]
there is the function for computing SSIM in utils/metrics.py

**Comment by tellMeWhyCan** [comment]
what do you mean " the SSIM of the paper is little different because it was computed using Matlab instead of Python"?

**Comment by davin11** [comment]
We used the official code:
https://ece.uwaterloo.ca/~z70wang/research/ssim/
https://ece.uwaterloo.ca/~z70wang/research/ssim/ssim_index.m
