### ISSUE TITLE
How to run the program for real SAR images.

### ISSUE THREAD

**Issue by PalgunaGopireddy** [grip-unina/SAR-CNN#4]
Hi @grip-unina 

I see that the code is only provided for the simulated SAR-like images.
How can I run the program for real-SAR images as told in the section 3.2 of the [paper](https://ieeexplore.ieee.org/document/8128234). 
I am jsut asking this question to know **how the dataset was generated using the procedure told in Fig.3 and `multilooking` is used for generating clean images** as told in last paragraph of section 2.

Please reply @grip-unina  even if you don't know the answer

**Comment by davin11** [comment]
We cannot provided the real-SAR images used in the paper
